Repository 4ian/GDevelop, pull requests merged in 2020-10, with the labels that each got.

#1979 Fix bug related to lighting (lack of webgl support)
  Extensions/Lighting/lightruntimeobject-pixi-renderer.js
  Extensions/Lighting/tests/lightruntimeobject.spec.js
Labels: 🏁PR almost ready: final fixes

#2010 [Platformer example] Clean the files
  newIDE/app/resources/examples/platformer/p1_jump.png
  newIDE/app/resources/examples/platformer/p1_stand.png
  newIDE/app/resources/examples/platformer/p1_walk03.png
  newIDE/app/resources/examples/platformer/p1_walk04.png
  newIDE/app/resources/examples/platformer/p1_walk05.png
  newIDE/app/resources/examples/platformer/p1_walk06.png
  newIDE/app/resources/examples/platformer/p1_walk07.png
  newIDE/app/resources/examples/platformer/p1_walk09.png
  newIDE/app/resources/examples/platformer/p1_walk10.png
  newIDE/app/resources/examples/platformer/p1_walk11.png
  newIDE/app/resources/examples/platformer/platformer.json
  newIDE/app/resources/examples/platformer/slimeWalk1.png
  newIDE/app/resources/examples/platformer/slimeWalk2.png
Labels: automerge

#2058 Increase and make responsive the selectors.
  newIDE/app/src/EventsSheet/ParameterFields/GenericExpressionField/index.js
Labels: ✨ enhancement

#2073 Remove Create function from object list only
  newIDE/app/src/InstructionOrExpression/EnumerateInstructions.js
Labels: automerge
