Repository 4ian/GDevelop, pull requests merged in 2020-09, with the labels that each got.

#1974 Fix warning shown when compiling GDevelop.js
  ExtLibs/CMakeLists.txt
Labels: automerge

#1975 Fix memory leak when reloading resources from objects
  newIDE/app/src/SceneEditor/index.js
Labels: automerge

#1976 Fix margins around renamed list items
  newIDE/app/src/ObjectEditor/Editors/TextEditor.js
  newIDE/app/src/ResourcesList/ResourceSelector.js
  newIDE/app/src/UI/SemiControlledAutoComplete.js
  newIDE/app/src/UI/TextField.js
  newIDE/app/src/UI/Theme/DarkTheme/index.js
  newIDE/app/src/UI/Theme/DefaultTheme/index.js
  newIDE/app/src/UI/Theme/NordTheme/index.js
  newIDE/app/src/UI/Theme/SolarizedDarkTheme/index.js
Labels: automerge, 🏁PR almost ready: final fixes

#1987 Remove PIXI hack in renderer objects
  Extensions/TiledSpriteObject/tiledspriteruntimeobject-pixi-renderer.js
  GDJS/Runtime/pixi-renderers/spriteruntimeobject-pixi-renderer.js
Labels: automerge

#1942 Add I18n to context menu and electron menu
  newIDE/app/src/EffectsList/index.js
  newIDE/app/src/EventsBasedBehaviorEditor/EventsBasedBehaviorPropertiesEditor.js
  newIDE/app/src/EventsBasedBehaviorEditor/index.js
  newIDE/app/src/EventsBasedBehaviorsList/index.js
  newIDE/app/src/EventsFunctionsExtensionEditor/EventsFunctionConfigurationEditor/EventsFunctionParametersEditor.js
  newIDE/app/src/EventsFunctionsList/index.js
  newIDE/app/src/EventsSheet/InstructionEditor/InstructionParametersEditor.js
  newIDE/app/src/EventsSheet/index.js
  newIDE/app/src/InstancesEditor/InstancePropertiesEditor/index.js
  newIDE/app/src/LayersList/LayerRow.js
  newIDE/app/src/MainFrame/ElectronMainMenu.js
  newIDE/app/src/MainFrame/Toolbar/PreviewButtons.js
  newIDE/app/src/ObjectEditor/Editors/SpriteEditor/index.js
  newIDE/app/src/ObjectGroupsList/GroupRow.js
  newIDE/app/src/ObjectsList/index.js
  newIDE/app/src/ProjectManager/index.js
  newIDE/app/src/ResourcesList/index.js
  newIDE/app/src/SceneEditor/Toolbar.js
  newIDE/app/src/SceneEditor/index.js
  newIDE/app/src/UI/ClosableTabs.js
  newIDE/app/src/UI/EditorMosaic/TagsButton.js
  newIDE/app/src/UI/List.js
  newIDE/app/src/UI/Menu/ContextMenu.js
  newIDE/app/src/UI/Menu/ElementWithMenu.js
  newIDE/app/src/stories/index.js
Labels: 🏁PR almost ready: final fixes

#1982 Update howler
  GDJS/Runtime/howler-sound-manager/howler.min.js
Labels: automerge

#1992 Add is fullscreen condition
  Core/GDCore/Extensions/Builtin/WindowExtension.cpp
  GDJS/GDJS/Extensions/Builtin/WindowExtension.cpp
  GDJS/Runtime/cocos-renderers/runtimegame-cocos-renderer.js
  GDJS/Runtime/events-tools/windowtools.js
  GDJS/Runtime/pixi-renderers/runtimegame-pixi-renderer.js
Labels: automerge

#1997 Feature/rtl
  newIDE/app/package.json
  newIDE/app/src/MainFrame/Providers.js
  newIDE/app/src/UI/Theme/DarkTheme/index.js
  newIDE/app/src/UI/Theme/DefaultTheme/index.js
  newIDE/app/src/UI/Theme/NordTheme/index.js
  newIDE/app/src/UI/Theme/SolarizedDarkTheme/index.js
  newIDE/app/src/UI/Theme/index.js
  newIDE/app/src/Utils/Memoize.js
  newIDE/app/src/Utils/i18n/RtlLanguages.js
  newIDE/app/src/stories/ThemeDecorator.js
Labels: 🏁PR almost ready: final fixes
