Repository 4ian/GDevelop, pull requests merged in 2021-08, with the labels that each got.

#2838 Asset store: Pixelate pixel art assets in viewer & make it bigger
  newIDE/app/src/AssetStore/AssetCard.js
  newIDE/app/src/AssetStore/AssetDetails.js
  newIDE/app/src/Utils/CssHelpers.js
  newIDE/app/src/Utils/GDevelopServices/Asset.js
Labels: ✨ enhancement, 🏁PR almost ready: final fixes

#2882 Add nearest support in image preview for pixel art resources
  newIDE/app/src/ResourcesList/ResourcePreview/ImagePreview.js
Labels: ✨ enhancement

#2933 Add translation in menu bar
  newIDE/app/src/MainFrame/ElectronMainMenu.js
Labels: automerge

#2870 Move variable event tools to their own file
  GDJS/GDJS/Extensions/Builtin/VariablesExtension.cpp
  GDJS/GDJS/IDE/ExporterHelper.cpp
  GDJS/Runtime/events-tools/commontools.ts
  GDJS/Runtime/events-tools/variabletools.ts
  GDevelop.js/TestUtils/GDJSMocks.js
Labels: 🏁PR almost ready: final fixes

#2953 Add missing translation tags
  Extensions/Physics2Behavior/JsExtension.js
  newIDE/app/src/Profile/SubscriptionChecker.js
Labels: ✨ enhancement

#2956 🔨 Removing cocos renderer files
  .vscode/c_cpp_properties.json
  Extensions/BitmapText/bitmaptextruntimeobject-cocos-renderer.ts
  Extensions/PanelSpriteObject/JsExtension.cpp
  Extensions/PanelSpriteObject/panelspriteruntimeobject-cocos-renderer.ts
  Extensions/ParticleSystem/JsExtension.cpp
  Extensions/ParticleSystem/particleemitterobject-cocos-renderer.ts
  Extensions/PrimitiveDrawing/JsExtension.cpp
  Extensions/PrimitiveDrawing/shapepainterruntimeobject-cocos-renderer.ts
  Extensions/TextEntryObject/JsExtension.cpp
  Extensions/TextEntryObject/textentryruntimeobject-cocos-renderer.ts
  Extensions/TextObject/JsExtension.cpp
  Extensions/TextObject/textruntimeobject-cocos-renderer.ts
  Extensions/TiledSpriteObject/JsExtension.cpp
  Extensions/TiledSpriteObject/tiledspriteruntimeobject-cocos-renderer.ts
  Extensions/Video/JsExtension.js
  Extensions/Video/videoruntimeobject-cocos-renderer.ts
  GDJS/GDJS/IDE/Exporter.cpp
  GDJS/GDJS/IDE/Exporter.h
  GDJS/GDJS/IDE/ExporterHelper.cpp
  GDJS/GDJS/IDE/ExporterHelper.h
  GDJS/Runtime/Cocos2d/cocos2d-js-v3.10.js
  GDJS/Runtime/Cocos2d/index.html
  GDJS/Runtime/Cocos2d/main.js
  GDJS/Runtime/Cocos2d/project.json
  GDJS/Runtime/cocos-renderers/cocos-bitmapfont-manager.ts
  GDJS/Runtime/cocos-renderers/cocos-director-manager.ts
  GDJS/Runtime/cocos-renderers/cocos-image-manager.ts
  GDJS/Runtime/cocos-renderers/cocos-tools.ts
  GDJS/Runtime/cocos-renderers/layer-cocos-renderer.ts
  GDJS/Runtime/cocos-renderers/loadingscreen-cocos-renderer.ts
  GDJS/Runtime/cocos-renderers/runtimegame-cocos-renderer.ts
  GDJS/Runtime/cocos-renderers/runtimescene-cocos-renderer.ts
  GDJS/Runtime/cocos-renderers/spriteruntimeobject-cocos-renderer.ts
  GDJS/Runtime/cocos-sound-manager/cocos-sound-manager.ts
  GDJS/scripts/lib/runtime-files-list.js
  GDJS/tests/tests/cocos-renderers/cocos-director-manager.js
  GDevelop.js/Bindings/Bindings.idl
  GDevelop.js/types/gdexporter.js
  newIDE/app/src/Export/BrowserExporters/BrowserCocos2dExport.js
  newIDE/app/src/Export/BrowserExporters/index.js
  newIDE/app/src/Export/ExportDialog.js
  newIDE/app/src/Export/GenericExporters/Cocos2dExport.js
  newIDE/app/src/Export/LocalExporters/LocalCocos2dExport.js
  newIDE/app/src/Export/LocalExporters/index.js
Labels: 🏁PR almost ready: final fixes

#2997 Increase the height of the description text field for extension
  newIDE/app/src/EventsFunctionsExtensionEditor/OptionsEditorDialog/ExtensionOptionsEditor.js
Labels: ✨ enhancement, 😤Non optimal UI behavior

#2995 [LinkedObjects] Avoid intersection calculus when nothing is picked
  Extensions/LinkedObjects/linkedobjects.ts
  Extensions/LinkedObjects/tests/linkedobjects.spec.js
Labels: 🏁PR almost ready: final fixes
