Repository 4ian/GDevelop, pull requests merged in 2021-04, with the labels that each got.

#2394 Make debug hitboxes & points usable in games
  Extensions/DebuggerTools/JsExtension.js
  Extensions/DebuggerTools/debuggertools.ts
  GDJS/Runtime/cocos-renderers/runtimescene-cocos-renderer.ts
  GDJS/Runtime/pixi-renderers/runtimescene-pixi-renderer.ts
  GDJS/Runtime/runtimescene.ts
  GDJS/Runtime/spriteruntimeobject.ts
  newIDE/app/public/res/point.png
Labels: 🏁PR almost ready: final fixes

#2509 Remove deprecated/unmaintained SkeletonObject extension
  .vscode/c_cpp_properties.json
  Binaries/README.md
  Extensions/CMakeLists.txt
  Extensions/SkeletonObject/Ask.ts
  Extensions/SkeletonObject/Bskeletonruntimeobject-cocos-renderer.ts
  Extensions/SkeletonObject/Bskeletonruntimeobject-pixi-renderer.ts
  Extensions/SkeletonObject/CMakeLists.txt
  Extensions/SkeletonObject/Cskbone.ts
  Extensions/SkeletonObject/Dskslot.ts
  Extensions/SkeletonObject/Eskarmature.ts
  Extensions/SkeletonObject/Extension.cpp
  Extensions/SkeletonObject/Fskanimation.ts
  Extensions/SkeletonObject/Gskeletonruntimeobject.ts
  Extensions/SkeletonObject/Hskmanager.ts
  Extensions/SkeletonObject/Isk-tools.ts
  Extensions/SkeletonObject/JsExtension.cpp
  Extensions/SkeletonObject/SkeletonObject.cpp
  Extensions/SkeletonObject/SkeletonObject.h
  GDevelop.js/Bindings/Bindings.idl
  GDevelop.js/Bindings/Wrapper.cpp
  GDevelop.js/types/gdskeletonobject.js
  GDevelop.js/types/libgdevelop.js
Labels: automerge

#2510 Fix export to Android/iOS failing if AdMob id was containing invalid characters
  GDJS/GDJS/IDE/ExporterHelper.cpp
  GDevelop.js/TestUtils/FakeAbstractFileSystem.js
  GDevelop.js/TestUtils/TestExtensions.js
  GDevelop.js/__tests__/Core.js
  GDevelop.js/__tests__/GDJS.js
Labels: automerge

#2514 Small fixes
  newIDE/app/src/CommandPalette/CommandManager.js
  newIDE/app/src/ObjectEditor/Editors/EmptyEditor.js
Labels: automerge

#2516 [Top-down] When diagonals are forbidden, allow an object moving vertically to change of direction.
  Extensions/TopDownMovementBehavior/tests/topdownmovementbehavior.spec.js
  Extensions/TopDownMovementBehavior/topdownmovementruntimebehavior.ts
  GDJS/tests/karma.conf.js
Labels: 🏁PR almost ready: final fixes

#2518 [Top-down] Stick controls now comply with the "allow diagonals" setting
  Extensions/TopDownMovementBehavior/tests/topdownmovementbehavior.spec.js
  Extensions/TopDownMovementBehavior/topdownmovementruntimebehavior.ts
Labels: automerge

#2484 Add a new preference for save or dismiss change on a dialog when a backdrop click happen.
  newIDE/app/src/EventsBasedBehaviorEditor/EventsBasedBehaviorEditorDialog.js
  newIDE/app/src/EventsSheet/EventsFunctionExtractor/EventsFunctionExtractorDialog.js
  newIDE/app/src/EventsSheet/InstructionEditor/EventTextDialog.js
  newIDE/app/src/EventsSheet/InstructionEditor/InstructionEditorDialog.js
  newIDE/app/src/EventsSheet/InstructionEditor/NewInstructionEditorDialog.js
  newIDE/app/src/KeyboardShortcuts/DetectShortcutDialog.js
  newIDE/app/src/LayersList/LayerEditorDialog.js
  newIDE/app/src/MainFrame/Preferences/PreferencesContext.js
  newIDE/app/src/MainFrame/Preferences/PreferencesDialog.js
  newIDE/app/src/MainFrame/Preferences/PreferencesProvider.js
  newIDE/app/src/ObjectEditor/ObjectEditorDialog.js
  newIDE/app/src/ObjectGroupEditor/ObjectGroupEditorDialog.js
  newIDE/app/src/PlatformSpecificAssetsEditor/PlatformSpecificAssetsDialog.js
  newIDE/app/src/ProjectManager/ProjectPropertiesDialog.js
  newIDE/app/src/SceneEditor/SetupGridDialog.js
  newIDE/app/src/UI/Dialog/index.js
  newIDE/app/src/VariablesList/VariablesEditorDialog.js
Labels: automerge

#2557 Fix potential crash when instances are selected and an object is deleted
  newIDE/app/src/InstancesEditor/InstancesSelection.js
  newIDE/app/src/InstancesEditor/InstancesSelection.spec.js
  newIDE/app/src/SceneEditor/index.js
Labels: automerge

#2589 Cancel default behavior from browsers when keyboard is used
  GDJS/Runtime/pixi-renderers/runtimegame-pixi-renderer.ts
Labels: 👀 Needs review

#2582 Add network and persistence configuration to firestore
  Extensions/Firebase/JsExtension.js
Labels: 👀 Needs review
