Repository 4ian/GDevelop, pull requests merged in 2021-09, with the labels that each got.

#3002 Add "object" term in timer action for object
  Core/GDCore/Extensions/Builtin/BaseObjectExtension.cpp
Labels: ✨ enhancement, automerge

#3022 [LinkedObjects] Objects can be picked from event functions.
  Extensions/LinkedObjects/Extension.cpp
  Extensions/LinkedObjects/linkedobjects.ts
  Extensions/LinkedObjects/tests/linkedobjects.spec.js
  tsconfig.json
Labels: 🏁PR almost ready: final fixes

#3084 Fix authorIds being saved in the prop elements of a project
  Core/GDCore/Project/Project.cpp
Labels: automerge
