Repository 4ian/GDevelop, pull requests merged in 2021-02, with the labels that each got.

#2269 Added any key released condition
  Core/GDCore/Extensions/Builtin/KeyboardExtension.cpp
  GDJS/GDJS/Extensions/Builtin/KeyboardExtension.cpp
  GDJS/Runtime/events-tools/inputtools.ts
  GDJS/Runtime/inputmanager.ts
  GDJS/tests/tests/inputmanager.js
Labels: 🏁PR almost ready: final fixes

#2275 Add expression normalize
  Core/GDCore/Extensions/Builtin/MathematicalToolsExtension.cpp
  Extensions/Video/videoruntimeobject.ts
  GDCpp/GDCpp/Extensions/Builtin/MathematicalTools.cpp
  GDCpp/GDCpp/Extensions/Builtin/MathematicalTools.h
  GDCpp/GDCpp/Extensions/Builtin/MathematicalToolsExtension.cpp
  GDJS/GDJS/Extensions/Builtin/MathematicalToolsExtension.cpp
  GDJS/Runtime/events-tools/commontools.ts
Labels: 🏁PR almost ready: final fixes

#2310 Add appid to the electron export
  GDJS/GDJS/IDE/ExporterHelper.cpp
  GDJS/Runtime/Electron/package.json
Labels: automerge

#2006 Refactor audio (pre)loading
  Core/GDCore/Extensions/Builtin/AudioExtension.cpp
  Core/GDCore/Project/ResourcesManager.cpp
  Core/GDCore/Project/ResourcesManager.h
  Extensions/SpatialSound/spatialsoundtools.ts
  GDJS/GDJS/Extensions/Builtin/AudioExtension.cpp
  GDJS/Runtime/events-tools/soundtools.ts
  GDJS/Runtime/howler-sound-manager/howler-sound-manager.ts
  GDJS/Runtime/types/howler.d.ts
  GDJS/Runtime/types/project-data.d.ts
Labels: 🏁PR almost ready: final fixes, 👀 Needs review

#2315 Migrate path finding from HSHG to RBush
  Extensions/PathfindingBehavior/pathfindingobstacleruntimebehavior.ts
  Extensions/PathfindingBehavior/tests/commonpathfindingruntimebehavior.spec.js
  Extensions/PathfindingBehavior/tests/legacypathfindingruntimebehavior.spec.js
  GDJS/package.json
  GDJS/tests/karma.conf.js
Labels: 🏁PR almost ready: final fixes

#2384 Add tests on the Platformer extension
  Extensions/PlatformBehavior/tests/platformerobjectruntimebehavior.spec.js
Labels: 🏁PR almost ready: final fixes
